### ISSUE TITLE
Heist single player bypass

### ISSUE THREAD

**Issue by Dane389** [L7NEG/L7NEG#1]
I want new feature in ultimate menu like that bypass casino and doomsday heist requirement for 2-4 players i want feature that can bypass this and can make casino and doomday heist solo.

**Comment by L7NEG** [comment]
Sure noted ✅️ there was a script already on yimmenu-lua or modest menu on unknowncheats.me that does this but it's a bit outdated so I will update it and add it on ultimatemenu repo.

**Comment by Dane389** [comment]
thank you please also include for apartment one and others heist that requires more then one people
